# Generated by Django 3.0.5 on 2020-04-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='question',
            name='upload_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
