# Generated by Django 3.0.5 on 2020-04-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitApp', '0002_auto_20200428_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
