# Generated by Django 3.0.5 on 2020-04-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubmitApp', '0003_auto_20200428_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubmitApp.Question'),
        ),
    ]
